nodeLinker: node-modules

packageExtensions:
  rc-image@*:
    dependencies:
      rc-motion: "*"
  react-smooth@*:
    dependencies:
      prop-types: "*"
  styled-components@*:
    dependencies:
      react-is: "*"

yarnPath: .yarn/releases/yarn-4.0.0-rc.45.cjs
