nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.2.2.cjs


packageExtensions:
  styled-components@*:
    dependencies:
      react-is: "*"
  rc-image@*:
    dependencies:
      rc-motion: "*"
  react-smooth@*:
      dependencies:
        prop-types: "*"